on: [push]
jobs:
  profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        working-directory: /code
      - name: Profiler
        uses: ./ # Uses an action in the root directory