on: [push]
jobs:
  profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Org action checkout
        uses: actions/checkout@v3
        with:
          repository: Alokit-Innovations/repo-profiler
          path: repo-profiler
      - name: Repo Profiler
        uses: ./repo-profiler
