on: [push]
jobs:
  profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Repo-profiler action checkout
        uses: actions/checkout@v3
        with:
          repository: Alokit-Innovations/repo-profiler
      - name: Run Repo-profiler action
        uses: ./repo-profiler
